language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0
before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - export CI="true"
script:
  - bin/test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
addons:
  postgresql: "9.4"
